### ISSUE TITLE
Autocompletion for usernames and groups

### ISSUE THREAD

**Issue by vinzv** [andstatus/andstatus#151]
It would be good to have usernames and group names automatically completed while typing.

**Comment by yvolk** [comment]
Nice feature, I guess it should have an option to fill "@Webfinger ID" (default or "@username"
?!

**Comment by moshpirit** [comment]
Well, mostly clients with this feature has both autocompletations

**Comment by yvolk** [comment]
I found an Android library component, android.support.v7.widget.AppCompatMultiAutoCompleteTextView "that can show completion suggestions for the substring of the text where the user is typing instead of necessarily for the entire thing".
Sample implementation was done recently by @Vavassor here: https://github.com/Vavassor/Tusky/issues/103

**Comment by yvolk** [comment]
Users autocompletion implemented in v.35.
![scr-autocomplete-users](https://user-images.githubusercontent.com/207716/28656275-acd84d0a-72a9-11e7-91da-b141271086e3.png)
