### ISSUE TITLE
Filter out replies not to me or my friends from Home timeline

### ISSUE THREAD

**Issue by Dragnucs** [andstatus/andstatus#160]
It would be very practical to have an option that allows us to hide replies to people we are not subscribed to.

For example I am subscribed to *A* but not to to *B*. *A* is subscribed to *B*. If *A* replies to *B*, I don't want to see this reply/notice.

**Comment by yvolk** [comment]
@Dragnucs @moshpirit You may start testing this new feature building from the Source code.

**Comment by vinzv** [comment]
Thanks for implementing! It works quite well with "real" replies. If there's not thread and the message starts with an @ symbol it doesn't grab it. Maybe that's a thing for another option like "Hide @-replies"?

![img_20151012_223252](https://cloud.githubusercontent.com/assets/74432/10438062/7c24a5d0-7131-11e5-983f-128b15e8023e.jpg)

**Comment by moshpirit** [comment]
I can't right now, I'm using an old device these days :(

**Comment by yvolk** [comment]
@vinzv "Hide @-replies" as an addition to "Hide replies..." looks like of a too narrow usage to me...

**Comment by vinzv** [comment]
Okay, good point. So maybe implement messages starting with "@username"
to be filtered as well as reply threads?

**Comment by yvolk** [comment]
I thought about this: this is not easy for GNU Social,  when  @username is used instead of Webfinger ID: it may refer to different people... but I may implement a simple/fast approach, matching as friends all @usernames (and thus not hiding them). 
HTML formatting may also interfere here, I'm afraid that stripping HTML of the fly may be too long.
Anyway, I will test this.

**Comment by Dragnucs** [comment]
Isn't there a text version that accompanies each notice?

**Comment by yvolk** [comment]
@Dragnucs Currently I implemented the filter for a Timeline view only.  All messages, even "hidden", are stored in a local database. 
So only one version of a message text is stored. And I am analyzing it on the fly... I thought now that stripping HTML before applying filters is needed for "Hide messages based on keywords" also, because it's not correct to filter by hidden HTML content...
...maybe I will go as far as to actually add another "plain text" column to a message table in order to use it for Search also?!

**Comment by Dragnucs** [comment]
Can't you filter them based on a regex that matches the text format OR 
the HTML format?

**Comment by yvolk** [comment]
@Dragnucs Could you give an example, I'm afraid didn't get you :-)

**Comment by Dragnucs** [comment]
/^(@\w+|<a .+>@\w+</a>)/

On 13 October 2015 19:45:32 WEST, Yuri Volkov <notifications@github.com> wrote:
>@Dragnucs Could you give an example, I'm afraid didn't get you :-)
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/andstatus/andstatus/issues/160#issuecomment-147809404

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by yvolk** [comment]
@vinzv I made it possible to filter replies to a User, which are not replies to a message.
If a message is not a Reply to another message, AndStatus checks if the message's body starts with @username and marks it as a Reply to a User with this username. So such "Replies to a User" are also filtered by this option

Please note that this new behaviour works only for messages, downloaded after installation of AndStatus v.20.1. (134)

v.20.1. Published at the Open Beta testing channel, please opt in here: https://play.google.com/apps/testing/org.andstatus.app

**Comment by Dragnucs** [comment]
Good.

**Comment by moshpirit** [comment]
931 errors on AIDE :(
Bq M5 - Android 5.0.2

**Comment by yvolk** [comment]
@moshpirit Please see #277 regarding compilation.

**Comment by moshpirit** [comment]
Oh, I didn't see your comment! thanks!

**Comment by yvolk** [comment]
Implemented in v.20
