### ISSUE TITLE
Custom timeline filters

### ISSUE THREAD

**Issue by moshpirit** [andstatus/andstatus#161]
Uses of the filters:
 - Highlight some posts with filtered words. (e.g. Andstatus → all the notes with "Andstatus" will be highlighted)
 - Hide some other posts with another filtered words. (e.g. NSFW → all the notes with "NSFW" won't appear anymore in our timeline (except if it appears in a mention))

**Comment by yvolk** [comment]
These are two additional types of filters/highlighter proposed in #160

**Comment by yvolk** [comment]
Filtering by keywords is implemented as part of #279. 
Except that there are no exclusions: messages are filtered out no matter if they are "mentions" or not...

Regarding message Highlighting, it should be in a separate "issue". Maybe we will create a "Highlighters" section and add "Mark replies to me" there also (because that is also a "Highlighter"...
