### ISSUE TITLE
Show RT/Repost in two points of a Timeline

### ISSUE THREAD

**Issue by moshpirit** [andstatus/andstatus#172]
I think that it's logical: I'm doing a repetition, anyway, it's more comfortable: if I Repost anything and later mark as favourite, I have to go upside of my timeline, favourite it and go down again to keep reading the Home TL.

**Comment by yvolk** [comment]
The problem is solved in AndStatus v.36:
The whole internal data model of the application has changed from working with "messages" to working with "[activities](https://www.w3.org/TR/activitypub/#Overview)", allowing to present social networks in a richer way and to solve many old problems. E.g. after reblogging of a message the message doesn't "jump" to the top of a timeline, as before: now you see a new "Reblog action" for this message at the top the timeline.
The same for Like/Favorite and Follow/"Stop following" actions...
