### ISSUE TITLE
Private conversation with selected recipient  (was: Tree-like threaded conversations on private messages too)

### ISSUE THREAD

**Issue by moshpirit** [andstatus/andstatus#181]
There's no way to read our replies to messages and I think that it could solve it. But the most important thing: we could read the conversations.

**Comment by yvolk** [comment]
While using latest versions of AndStatus, I encountered a situation in Pump.io, when I have a "Direct" message as a part of a "Public" conversation. I mean, one of replies is to myself personally.
Current implementation doesn't allow me to "Reply" to that "Direct message" - I can only post a Direct message, thus loosing the context (the whole conversation).

This led me to these conclusions:
1. We really need a Reply to a private message for Pump.io
2. AndStatus has to remember/analyze all recipients, not the first one only. In this case I suppose the author replied not only to myself, but to other users or to a "Public" group also, but we don't see this in AndStatus now...
At least, AndStatus has to analyze, if a "Public" recipient is present, in order to correctly mark a message as Public/Private ("Direct" for now...)
3. Apparently current Public/Direct classification doesn't cover situations, when "Me" is not the only recipient, but the message is not sent to "Public" group. Thus we will have the three groups of messages from a privacy point of view:
   1. Public (accessible by everybody, even by not authenticated visitors)
   2. Private (accessible by a restricted group/list of recipients)
   3. "Direct" (one to one communications). Is this term the best for this list? - Maybe not, but people are used to it and to its meaning...

**Comment by aroquen** [comment]
@yvolk In the gnusocial web interface, type 3. is called "private messages" but "direct messages" sounds fine as well. Looking forward to having all this implemented in andstatus at some point!

**Comment by yvolk** [comment]
@aroquen Please see this discussion: https://loadaverage.org/conversation/6786094#notice-6789905
In short: in GNU Social terms "Private message" and "Direct message" refer to different tools/features. Both are poorly implemented at a server side, so improvement from GNU Social side is needed first.

And I didn't hear about "Private messages" in GNU social (as they are not part of "Twitter compatible" API, which AndStatus uses?!).
Having difficulties to figure out, which dent/message is private (in Pump.io), I recently implemented a function, which tells if attachment _may_ be private :-)
For now, I personally assume that only "Direct messages" are really private.

As to future implementations, in order to avoid confusion, I suggest to add an explicit "Privacy" attribute to any message (defaults to Public - we are in a Social network!). This attribute may have more than two values ("private", "public"), but maybe also something like "one-to-one" and "group", refering to the concrete "one" person and one group and meaning concrete lists of users, having access to the message. This attribute should not allow a system/user to misinterpret the scope of privacy.

**Comment by aroquen** [comment]
> And I didn't hear about "Private messages" in GNU social (as they are not part of "Twitter compatible" API, which AndStatus uses?!).

You can see it in the web interface:
![screenshot - 040315 - 13 47 11](https://cloud.githubusercontent.com/assets/4344578/6483838/d0c752c4-c275-11e4-8910-502fcd5c696d.png)

> Having difficulties to figure out, which dent/message is private (in Pump.io), I recently implemented a function, which tells if attachment may be private :-)
For now, I personally assume that only "Direct messages" are really private.

As far as I can tell from my tests, private notices in GNUSocial are indeed private, i.e. they can't be seen by people who don't belong to the group to which the private message was sent to. And private notices in a private site can't be seen from the outside. The loadaverage site is down so I don't know if I am missing something important. In any case, the design is that notices can be private or public in GNUsocial.

> As to future implementations, in order to avoid confusion, I suggest to add an explicit "Privacy" attribute to any message (defaults to Public - we are in a Social network!). 

Yes, indeed, like the GNUSocial web interface 
![screenshot - 040315 - 13 48 52](https://cloud.githubusercontent.com/assets/4344578/6483885/535675a8-c276-11e4-8e92-67d4d905c127.png)
Concerning the default, I'd personally let the user choose via some settings but that's a minor thing.

**Comment by yvolk** [comment]
Meanwhile behaviour for Pump.io was fixed: #271 - replies to private messages remain private.

**Comment by yvolk** [comment]
Implemented "Private conversation with selected recipient". Now clicking "Open conversation" on a Direct message (for GNU Social and Twitter) opens a list of messages between the two recipients. 
Pump.io supports private conversations natively, so for Pump.io "Reply" to a Direct message is now enabled, which allows to have different "conversations" with the same recipient (as for public conversations).

Available since v.30.01
