### ISSUE TITLE
Notices from users with remote accounts are not pulled

### ISSUE THREAD

**Issue by aroquen** [andstatus/andstatus#210]
I have an account on gnusocial.no and follow a few remote groups. Notices sent to these groups from other servers are not loaded by AndStatus (v. 14.0). It only shows notices from people with an account on gnusocial.no. I don't know if this is a server issue, but everything works fine via the web interface.

**Comment by aroquen** [comment]
It was either a server issue or the fact that notices appear chronologically in AndStatus. I seem to find all posts now. Closing it.

**Comment by aroquen** [comment]
Upon closer inspection, there are indeed many notices I don't receive. They are replies to a message (which I received because I subscribed to a group) made by users with an account on a different server. It seems like I only receive such messages when they explicitly include the !group I have subscribed to.

**Comment by yvolk** [comment]
1. Please see these problem, which turned out to be a GNU social bug, related to remote users: HTTP error 400 Reloading User timeline from some Users at GNU Social Servers #174
2. I have accounts on several GNU social servers. And I'm often noticing that a message, which is a reply to some earlier message at one server appears as a single message (without a reference to the previous message) at another server.
3. AndStatus doesn't have a "Group" notion yet. This shouldn't influence receiving subscribed posts, but anyway...

**Comment by yvolk** [comment]
@aroquen I tend to think that this is a limitation of "Twitter based API" which AndStatus uses for GNU social?!

**Comment by aroquen** [comment]
Concerning 2. I also saw that, but not always... the behavior looks inconsistent already from the web interface. However, it's true that there are additional issues on AndStatus and I can only guess is due to the bug you point out. So this will be fixed if/when GNUSocial will implement the timeline for remote users? I just wonder how this works from the web interface though, and whether AndStatus could fallback to that in case the timeline is not implemented.

**Comment by yvolk** [comment]
My current understanding is that in order to see conversation the same way your followed User sees it, you have to follow him by your account at the User's home instance. 
E.g. a User from quitter.se should be followed by you@quitter.se

**Comment by yvolk** [comment]
It appears like an expected behaviour on GNU social: you will not see all replies to a conversation, see this dicsussion: https://loadaverage.org/conversation/6742311
