### ISSUE TITLE
Get open instances appears like a + insted of the phrase

### ISSUE THREAD

**Issue by moshpirit** [andstatus/andstatus#230]
In my mobile phone it only appears the icon in the Action bar, not the phrase. It's a Sony Xperia SP (Android 4.3). I report it to change the User Manual and name the icon (it's named in Spanish)

OK, I don't know exactly how this function works, you named a list maintened by the GNU proyect but I don't know where's the list (using ß version)

**Comment by yvolk** [comment]
You will find all information on this feature here: https://github.com/andstatus/andstatus/issues/84
"+" icon is not for Discovery - it's really to Add new Microblogging system. 
Icon for discovery is the same as for "Global search".

**Comment by yvolk** [comment]
In general, regarding an icon instead of a text in Android "Action bar".
This is expected Android Action bar behavior ( a "design pattern"): every item on this bar may have alternative presentation as an icon (with a sort of tooltip) and a Text,  shown in an "Action overflow" (see http://developer.android.com/design/patterns/actionbar.html )
