### ISSUE TITLE
Unable to add identi.ca account

### ISSUE THREAD

**Issue by hubutm20** [andstatus/andstatus#240]
This is what it's not appearing for me "A web browser screen will open with your Pump.io instance’s Login dialogue. Enter your plain account name again (without @identi.ca this time) and your password, then tap "Login" ". The Pump.io server is empty https://imgur.com/ytu00qg
I have added Quitter.se account and it's working. Android 4.2.2 AndStatus 15.0

**Comment by yvolk** [comment]
1. First strange thing is that you added another "Microblogging system". Please try to start with existing "Pump.io". 
2. Absence of a hostname for Pump.io is by design: users from different hosts share the same "Microblogging system"...
3. Please post a screenshot of an Account settings screen: 
3.1. before you press "Add this account" button.
3.2. After you press "Add this account" button.

**Comment by hubutm20** [comment]
The first screenshot https://imgur.com/977Jp84, when adding my username
followed by "@" the "@" sign is added with one space in front of it and
that is not normal.
Here is the second screenshot https://imgur.com/gDNOmdY
Here the third https://imgur.com/ubNZzMC
And final https://imgur.com/0ibejRK

2015-02-27 20:03 GMT+02:00 Yuri Volkov <notifications@github.com>:

**Comment by yvolk** [comment]
1. On the second screenshot I don't see any spaces in front of "@", I see "hubutm20@identi.ca". What is wrong?
2. After your second screenshot you should see this:
![scr-adding-pumpio-account-2](https://cloud.githubusercontent.com/assets/207716/6424939/0a85f758-bf20-11e4-8d18-feeb7e617e8b.png)
3. As I understand, you are automatically returned to "Settings" screen and "1 existing account" is that Twitter account, about which you wrote?!
4. Which AndStatus version are you using, and from where did you download the andstatus.apk ?

**Comment by hubutm20** [comment]
I forgot to make a screenshot with the @ problem and mention that "1
existing account" is Quitter.se.
The apk it is from GooglePlay, the version is 15.0 as is shown in
settings/apps


2015-02-28 7:05 GMT+02:00 Yuri Volkov <notifications@github.com>:

**Comment by yvolk** [comment]
I think that problem with spaces around "@" are caused by your current keyboard auto correction...
Do you think this could be a cause of the "blank screen"?

Anyway, as I cannot reproduce the account creation problem,  your help in getting any logs created after pressing the "Add this account" button is critical...
Please read on logging: https://github.com/andstatus/andstatus/issues/225
