### ISSUE TITLE
[pump.io] Conversation doesn't display replies from users I don't follow

### ISSUE THREAD

**Issue by jamessan** [andstatus/andstatus#274]
For pump.io instances (identi.ca is the one I happen to use), when someone I follow has replies to their note, I don't see those replies.  Typically I notice this because the author of the original note responds to the other responses, so I notice that I'm only seeing part of the conversation.

As an example, [this post](https://identi.ca/liw/note/ca9Za6vmSUWViWjYGdk6HQ) and all of liw's replies show up in my timeline and the conversation view of the original post.  However, I had to `Open on internet` to see Claes' response.

If it helps, I can post the contents of what the API [output](https://identi.ca/api/note/ca9Za6vmSUWViWjYGdk6HQ) is, since that requires logging in.

**Comment by yvolk** [comment]
Hi @jamessan,
Please read this #190 "[pump.io] Don't make a Reply ("Comment") public" and linked issues. They uncover some internals of how Pump.io works. From what I can think of now, you don't see replies to other people in your "Timeline" in AndStatus, because Pump.io server thinks that the replies are not addressed to you. 
I don't know: maybe that replies are not "Public" or this is simply a Pump.io's bug (and this is why you can see these replies via Web interface).
I wish Pump.io team reappear and start fixing such bugs. I remember to post bug report to Pump.io two years ago, it's still open: https://github.com/e14n/pump.io/issues/848 
See related issue here: #48 "Pump.io replies to replies get lost".

Anyway, I don't think we can fix this without Pump.io developer's help?!

**Comment by jamessan** [comment]
The [API response](https://gist.github.com/jamessan/49263c686197bb73aa72) shows the reply that I'm not seeing in AndStatus.  Also, [Pumpa](https://pumpa.branchable.com/) displays Claes' response in my timeline.

**Comment by yvolk** [comment]
@jamessan The API response, which you presented, is obviously a result of a request of the concrete known "note". The question is why it is not shown in your home timeline ("inbox").
Could you try to look it up in the Timeline the same way?  (Or make sure that it's not there)

**Comment by yvolk** [comment]
BTW, AndStatus allows to log all API responses (JSON files) "Log network level messages"
So you can see, what AndStatus requests and what it gets...

**Comment by yvolk** [comment]
Hi @jamessan. 
1. Reading you first post again I realized that you _do_ see the "note" in AndStatus, but you don't see Claes' "comment" on it?! 

2. And I understood, why "Pumpa" could show that comment. This is because when AndStatus receives a "note" or "comment" (single or as an item from a Timeline) it doesn't parse "**replies**" (where I see that comment is located in your json file).
So it looks like that comment really was not sent to you as an item of a timeline, but could be received as part of the "note"?!

3. None the posts / comments in the JSON file have "to" element, which should show recipients. So it's really unknown, how the server should interpret the scope of recipients... Even if they are public or private...

**Comment by jamessan** [comment]
1. Yes.
2. Shouldn't replies be parsed?  That's essentially the core of my request.  I want to be able to see the replies to a note, even if I wouldn't normally see that user's activity.
3. According to [pump.io's API](https://github.com/e14n/pump.io/blob/master/API.md), the lack of a `to` means

> Default addresses are added if an activity is posted to the activity outbox with no address properties. We try to be reasonable with the defaults, as follows:
>
>* If an activity has an object that is inReplyTo another object, the addresses for the "post" activity of the original are used.
>* If an activity is an "update" or a "delete" of an object, the addresses for the "post" activity of that object are used.
>* If an activity has an object that is a "person", the person is added as a to address.
Otherwise, the actor's followers are added as a cc address.

Since the reply didn't have a `to` but the object that it is `inReplyTo` is something visible to me, then the reply should be as well.

P.S. I'll post the inbox response when I get to a computer where I can easily post it.

**Comment by yvolk** [comment]
2. Yes, I think this is easy to add. Will do this and reply to this issue.
Do you think I can use a JSON that you provided as a data for a unit test?
3. As the original "note" doesn't have "to" either, the "defaults" are not applicable :-) So the logic of the server is still unspecified :-(

**Comment by jamessan** [comment]
Thank you! :) Yes, you can use the JSON for a unit test.

**Comment by jamessan** [comment]
Claes' reply is not in my inbox, while Liw's replies to himself are.

The [entry](https://gist.github.com/jamessan/d59a73a79d665195e1d7) for Liw's original post in my inbox contains appropriate `to`/`cc` information, so there is a way to collect it even if it isn't repeated in the `api/note/` response.

**Comment by yvolk** [comment]
1. "The entry for Liw's original post in my inbox contains appropriate to/cc information, so there is a way to collect it even if it isn't repeated in the api/note/ response"
I think that this is a bug / design mistake of Pump.io.  "to" attribute should not be an optional part of a "note"/"comment".

2. As to the initial problem of this issue, it appeared not a Pump.io's or AndStatus bug as showing in a Timeline messages from users, which you are not subscribed to, is not required. 

I will create separate focused tickets on what may be done  and then will close _this_ issue.
