### ISSUE TITLE
Global "Mute filters" to hide messages by keywords

### ISSUE THREAD

**Issue by vinzv** [andstatus/andstatus#279]
It would be useful to have timelines filtered by individually defined keywords. This way the user can clean out unwanted contents.

**Comment by yvolk** [comment]
Currently we have (1) a list of Timelines to switch between. Actually, these are predefined filters of all cached messages. 
In order to have exact filtered list, User has to set (2) "combined" and, if not combined,  (3) an Account also. 
In addition, you may apply (4) a Search to the list thus filtering it by a keyword.
So, the resulted filter is defined by the four individual settings. 

In order to ease filter switching, I think that we should create the fourth filtering "gear": "Filters".

Each filter will be persistent, have easily recognized Title,  and define ALL filtering parameters,  including keyword filtering. So the only  difference with current state would be: 
ability to switch to your custom stored filter in one / two clicks?!

**Comment by vinzv** [comment]
Just to make it clear (maybe I wasn't stating my wish misinterpretable): I want to hide message by keyword, similar to e.g. Fenix for Twitter's "mute filter" feature. See screenshot.
![screenshot_2015-07-15-11-34-53](https://cloud.githubusercontent.com/assets/74432/8695529/c4641926-2ae5-11e5-96cf-f37017ab77c3.png)

**Comment by yvolk** [comment]
@vinzv So, you are talking about some global "Mute filter(s)" applied to _all_ views,  including Timeline AND Conversation view?!

**Comment by vinzv** [comment]
Am 15. Juli 2015 18:17:29 MESZ, schrieb Yuri Volkov <notifications@github.com>:
>@vinzv So, you are talking about some global "Mute filter(s)" applied
>to _all_ views,  including Timeline AND Conversation view?!
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/andstatus/andstatus/issues/279#issuecomment-121666306

Yep, or at least for timeline as there it's more important.

**Comment by yvolk** [comment]
@vinzv You may start testing this new feature building from the Source code.

**Comment by yvolk** [comment]
Released in v.20

**Comment by yvolk** [comment]
Example of usage:
In order to hide notifications on favorites messages:
Go to AndStatus Settings -> Filters -> "Hide messages based on keywords or exact phrases".
And type in double quotes this: "favorited this message"

Please note that a phrase to hide should be exactly the same as you type it, even the same number of spaces between words...

**Comment by moshpirit** [comment]
This exclude notifications when someone favorites your posts :( wouldn't be possible to add some "including" filter such us "favorited something by @ yourusername" or creating some setting by adding a rule inside the code. 

I'm not sure how this works at the present time but if it reads the post and then it hide it, I don't think it would be that difficult to do something like:

``` 
if post contains "favorited something by @ username" & filters=true & filter_except_the_user=false:
    hide post
    else 
    show post```

I called "filters" to this current feature and "filter_except_the_user" to this feature I'm requesting :) 

Sounds good or it's way more complicated than what I'm imagining? haha

**Comment by moshpirit** [comment]
Or even better: an option to exclude the words just from the timeline and not from notifications

**Comment by yvolk** [comment]
> Or even better: an option to exclude the words just from the timeline and not from notifications
@moshpirit Using #ActivityPub terminology, you suggests:
1. To detect GNU Social "favoriting actions" formatted like ordinary notes (using "somebody favorited something by otheruser:" "favoriting prefix") during processing of downloaded timelines.
2. And convert such notes into LIKE actions of original ("favorited") notes. Text of that "original" note should be re-constructed by removing the "favoriting prefix".

As a result timelines won't contain that "somebody favorited something by otheruser:" words, but will have LIKE (favoriting) actions of somewhat not fully reconstructed "favorited notes"...

**Comment by moshpirit** [comment]
But this is only terminology, right? If so, it doesn't fix my issue :\

**Comment by yvolk** [comment]
This is _not_ only terminology, I proposed different solution that:
1. will allow you to see that somebody favorited your note (in Notifications timeline) 
AND 
2. "somebody favorited something by otheruser:" words will be automatically removed from all incoming notes.

Why isn't this what you need?

**Comment by moshpirit** [comment]
That exactly is :D thank you so much!!

**Comment by yvolk** [comment]
@moshpirit Thank you for the suggestion. I seemed to wish this also, but your request made it clear, what should be done.
