### ISSUE TITLE
Asynchronous image loading to a Timeline - Hang Problem in Timeline Activity

### ISSUE THREAD

**Issue by brok85** [andstatus/andstatus#303]
Dear AndStatus Developers,
I am implementing a hang-bug detection tool and I am analyzing AndStatus with it. I found that the main thread of AndStatus, frequently calls 

Bitmap bitmap = BitmapFactory.decodeFile(...);

after calling the drawableFromCursor function in the AttachedImageDrawable class. As also the Android documentation states, the decode* functions should not be executed on the UI thread. As a result, moving the execution of the BitmapFactory.decodeFile(...); off the main thread leads to higher responsiveness of the app while the user is scrolling through the timeline activity of AndStatus.

I tried moving the BitmapFactory.decodeFile(...) call off the main thread and the improvements in AndStatus responsiveness are noticeable. 

Do you think that moving the decodeFile call off the main thread would be a valuable solution for improving AndStatus responsiveness?  

Thanks for any information,
I hope I can help improve AndStatus.

**Comment by yvolk** [comment]
@brok85 Thank you for a tip.
It's not that hard for me to preload into memory all images, which are present in a Timeline. I didn't do this yet, because I'm afraid this may cause memory overloading, because there may be many images.

Currently, as I understand, attachments are being loaded on demand, when a ListView is preparing to show some items to a User. Not all images at once.
Am I right?!

Yes, sometimes I notice a delay in scrolling a Timeline, when some large image is to be shown. But this occurs separately for each image. Only small number of list items are fully loaded at the same time, as I think.
?!

**Comment by brok85** [comment]
@yvolk Thank you so much for your reply!

I have noticed the hangs with an account as Twitter in the timeline. Indeed, twitter-like accounts have more images than other accounts as GNUsocial for each post. In addition, more then 2 or 3 images could be present at the same time on the timeline even without scrolling. Many of those images could be quite expensive to load in terms of computation on the main thread. Probably that is why I often noticed a delay in the responsiveness since the main thread handles only few user inputs between a load and another. In summary, I think the hangs are more noticeable when the user tries to scroll fast trough the timeline.

Do you think that in the future you will change the code to handle this situation?

**Comment by brok85** [comment]
@yvolk Actually, instead of preloading all the images into memory, the problem may be also solved by starting an asyncTask for each image, and let the onPostExecute method to update that bitmap. In this way you may avoid the problem of memory overloading, load only images on demand, and improve responsiveness.

What do you think?

Thank you so much for any reply!

**Comment by yvolk** [comment]
@brok85 I agree, asynchronous image loading from storage may be done in AsyncTask, something like you described and e.g. here http://stackoverflow.com/questions/6486038/listview-asynchronous-image-loading-strategy.
In order to ensure smooth scrolling, we need to set an image to some blank one of the same size and then start loading of a proper image. 
List item already has message id, which may be used for searching the item after Drawable is ready...
You could speed this up by providing pull request with your implementation.

**Comment by yvolk** [comment]
I started implementation of image cache from http://developer.android.com/training/displaying-bitmaps/cache-bitmap.html
No async decoding yet.

**Comment by yvolk** [comment]
Caching implemented greatly reduces number of  BitmapFactory.decodeFile calls: up to several times. Especially when timeline is being updated.
@brok85 Please see if these changes improved performance? (Not released yet, see in latest commit...)

**Comment by yvolk** [comment]
AndStatus v.22.16 published to the Open Beta testing channel https://play.google.com/apps/testing/org.andstatus.app
In order to make timeline scrolling smoother all avatars and attachments are loaded in a background now. Special in-memory cache introduced to further improve responsiveness. Statistics of caches and async loaders is shown in "Commands in a queue".

**Comment by brok85** [comment]
Thanks for the feedback!
I will test the new version as soon as I can and I will let you know.

Thanks a lot!

**Comment by yvolk** [comment]
@brok85 BTW It would be interesting to look at your "hang-bug detection tool"...

**Comment by brok85** [comment]
well we are still in the development phase. Hopefully it will be completed soon :)

**Comment by yvolk** [comment]
Fixed in v.22.18

**Comment by brok85** [comment]
Hi yvolk,
sorry for replying so late. I have tested the latest AndStatus version (master version downloaded today) and it seems that the problem listed before is fixed! Now the timeline scrolls very smoothly.

However,  browsing trough the app I could find another possible cause of a hang-bug that occurs every time the about Andstatus button in settings is clicked. In particular, the following extracts of stack shows the two APIs that most probably cause the hang-bug:

1) org.andstatus.app.util.Xslt.toHtmlString(Xslt.java:67) -> org.apache.xalan.transformer.TransformerImpl.transform(TransformerImpl.java:1123)

2)  org.andstatus.app.util.Xslt.toHtmlString(Xslt.java:64) -> org.apache.xalan.processor.TransformerFactoryImpl.newTransformer(TransformerFactoryImpl.java:776)

I think that also in this case the responsiveness of AndStatus would improve by moving those two  APIs off the main thread. What do you think?

Thanks for any info,
Hope to help improving AndStatus!
