### ISSUE TITLE
"Users in message" misses users unknown to GS host

### ISSUE THREAD

**Issue by vinzv** [andstatus/andstatus#315]
If a user is unknown to the current host because no one ever followed him from there (most likely for relatively new users) it isn't shown in "users of message" view. Information should be fetched there on demand.

![screenshot_2015-12-06-03-14-51_org andstatus app](https://cloud.githubusercontent.com/assets/74432/11611338/8d465d06-9bc8-11e5-95dd-dc89966b1927.png)

**Comment by yvolk** [comment]
1. The problem is that e.g. in this concrete example we even don't have "WebFingerID" of the user, so it is impossible to reliably resolve the user?!
2. Suppose that you typed WebFingerID e.g. someuser@somehost.net and current GNU Social server still doesn't return any information on this user. How to connect to that "somehost.net" ?
BTW pump.io solved that problem - it has a way to register automatically on any federated server...

**Comment by vinzv** [comment]
I see. So it's merely a GNU Social problem.
I will open an issue over a their repo.

**Comment by yvolk** [comment]
It came to me that specially for GNU SOCIAL I could add "Lookup in other Social networks" context menu item. This new item appears for a GNU Social User, if accounts in more than one Social network of "GNU Social" type configured in AndStatus.
?!

**Comment by vinzv** [comment]
Sounds good, but there must be some feature in Gnu Social which pulls in unknown user's data. Not sure if thats available via API.
