### ISSUE TITLE
No direct URL shortener

### ISSUE THREAD

**Issue by joeyvanderbie** [andstatus/andstatus#32]
When writing a message it is not possible to shorten the URL before sending. Identi.ca does shorten the URL, but after the message is send. Giving the user the option to shorten the URL before sending will result in having more characters left to type, especially with large URLs.

I would advice a URL shortener button to the right top of the "send" button. There seems to be no real standard on how to show an URL shortener button, but I really like the Seesmic approach. It's an icon with a chain being compressed by to arrows(triangles). Looking around the web gives you similar approaches.
![seesmic-post-screen](https://f.cloud.github.com/assets/134150/295254/54567040-946d-11e2-901e-edc0d97ba9fa.png)

Also the Microsoft Windows Phone URL shortener icon is an option http://www.windowsphone.com/en-us/store/app/url-shortener/7cc02e37-a978-e011-986b-78e7d1fa76f8

**Comment by yvolk** [comment]
Some time ago we had the conversation on this topic: https://quitter.se/notice/3129892

**Comment by drym3r** [comment]
I understand that quitter.se it's maybe the only server with the 140 char limit, but it's very used, so maybe adding an option to shorten with a custom shortener like your.ls (which is what qvitter uses) would help a lot of people. Also, it's length it's still on 19 chars.
Btw, qvitter (quitter.se included) now has shortener included, and can be used by anyone.

**Comment by yvolk** [comment]
@drym3r So it looks like the only step needed is to turn the URL shortener on at quitter.se:
for posts, which are more than 140 characters long, automatically shorten all URLs (otherwise such posts would be rejected by the server).
?!

**Comment by drym3r** [comment]
It does not work like this, as far as I know. The url are not automatically shortened in any qvitter instance. But even if it was like you say, GNU Social nodes that hadn't qvitter installed wouldn't have the shortener option.
On the andstatus side, if it had a button, it could recalculate the chars left when pressing it.

**Comment by yvolk** [comment]
@drym3r We are discussing very artificial case, created by  quitter.se admins. These admins could solve  your problem by simply changing some configuration item. But they don't do this,  because they think 140  characters is a proper limit for _this_ site.
My understanding is that quitter.se is not for people who want to post long texts. So if you need longer texts,  quitter.se is not for you. Don't search for workarounds,  but better choose another instance and forget about problems with writing and reading long posts.

**Comment by yvolk** [comment]
@drym3r BTW Your two above posts in this thread have 364 and 324 characters...

**Comment by drym3r** [comment]
**@yvolk**:
> @drym3r We are discussing very artificial case, created by quitter.se admins. These admins could solve your problem by simply changing some configuration item. But they don't do this, because they think 140 characters is a proper limit for this site.

But is not only for quitter.se. The shorteners have some options that some people (not me, but I really would like a shortener) that can tell how many visits had had some url in particular. Using qttr.at, since it's using yourls, it's easy to do it, it has an api. 

**@yvolk**:
> My understanding is that quitter.se is not for people who want to post long texts. So if you need longer texts, quitter.se is not for you. Don't search for workarounds, but better choose another instance and forget about problems with writing and reading long posts. 

But this is not about long posts, it's about long urls. 

**@yvolk**:
> @drym3r BTW Your two above posts in this thread have 364 and 324 characters...

But they haven't any url on it :P
