### ISSUE TITLE
Allow to select, which individual timeline to sync automatically, including User and Favorites

### ISSUE THREAD

**Issue by Yowlen** [andstatus/andstatus#339]
Due to the lack of the conversation part in the public Twitter API, I use the mobile site in combination with AndStatus. I've noticed that if AndStatus has a tweet in its cache already, & I favorite/retweet it on the site, AndStatus won't update those when resyncing. It can then cause soft errors in the "Commands in queue" area if I attempt to also favorite/retweet them in AndStatus.

**Comment by yvolk** [comment]
1. Yes, AndStatus cannot Sync list of Favorites yet.
Twitter has the API for this: https://dev.twitter.com/rest/reference/get/favorites/list
We could implement this, so User could switch to "Favorites" timeline and start "Sync with Internet".

2. Regarding Syncing retweets (by Authenticated User), I don't even see such API in Twitter...

**Comment by Yowlen** [comment]
Did a quick check on that link, & saw this:
https://dev.twitter.com/rest/reference/get/statuses/retweets/%3Aid

Wouldn't it be possible to get the retweets from this?

**Comment by yvolk** [comment]
@Yowlen The API that you found returns retweets of a single known tweet, not "recent retweets of all my tweets since..." as we are needed in this case. 
It could be used, but in a context of a single tweet. E.g. in a Conversation view, which had one "Central" tweet marked with a light border...

**Comment by Yowlen** [comment]
Ah, didn't notice that part. Well, let's try something different. If the tweet I favorite/retweet from the mobile site hasn't been synced into AndStatus yet (including when adding the account, ofc), it registers fine, so something in that part of the code gives the status on both of them. Do you fetch the status for each tweet individually there, or is it given in the main timeline API? If it's the latter, perhaps an option to manually resync older tweets (or automatic toggle in the settings with wifi-only sub-option to prevent data overusage) would work to update these?

**Comment by yvolk** [comment]
1. Unfortunately Twitter API doesn't have a notion of a User Action (which e.g. Pump.io has). That is actually what you need to be synchronized between devices: your user's (your accounts') actions, including posting, favoriting, retweets...

2. Could you try to sync a "User" Timeline manually. I think that timeline should show you new posts/retweets, which you did on other devices?!

3. Notifications "A user favorited something by..." - these are not "machine understandable" plus they are not sent to yourself...

4. Giving a User ability to resync since some date in the past may really help, but this will mean a lot of unnecessary traffic and it's hard to understand, what was updated...

**Comment by Yowlen** [comment]
Syncing the user timeline does solve the issue on the main timeline, as you suspected in (2). In fact, I tested two different cases, & it syncs the favorites/retweets not only when syncing the tweet's author, but the login user (the one I tweet as), too. This sparks a new idea for me. The code might be able to be duplicated to refresh the user's timeline in the background to keep it updated like the home timeline currently is.

**Comment by yvolk** [comment]
I agree, good idea:
Add a new option: "Sync User Timeline" with this description:
"Syncing User's timeline allows you to receive your own updates made via other devices or Web interface"
?!

**Comment by Yowlen** [comment]
Sounds great to me. Can't wait to give it a shot. :)

**Comment by Yowlen** [comment]
Actually, I just noticed that syncing the User timeline doesn't actually solve the Favorites issue, at least not all the time. I'm unsure why it worked before, but I saw one or two tweets today that didn't update with the User timeline. The good news is that I got it to update by syncing the Favorites timeline.

I also got to thinking that maybe it would be better to implement a checkbox for each timeline so the user can decide which ones are important. Combined with an ability to create custom timelines (such as timelines that follow a specific user like Twidre has), this could be much more versatile in function & allow the user to decide what they want to stay updated on.

**Comment by yvolk** [comment]
This question/answer shows, how to have multiple sync adapter items (different timelines in AndStatus...) for each account: http://stackoverflow.com/questions/30998063/android-multiple-sync-adapter-items-like-google-account

**Comment by yvolk** [comment]
Since v.27.0 Individual timelines can now be managed separately in the "Manage Timelines" table (in a menu of a list of messages and also in Settings->Timeline). For each timeline you can define: if it's shown in a list of available timelines and if it's synced automatically...
![managetimelines](https://cloud.githubusercontent.com/assets/207716/16662524/bae19fee-4480-11e6-910d-f7c8a722ab04.jpg)

**Comment by yvolk** [comment]
@Yowlen BTW now your account's "User" timeline is called "Sent"

**Comment by yvolk** [comment]
Syncing of individual timelines implemented in v.27
