### ISSUE TITLE
Unable to Reply to messages; draft message created, saved, and uneditable

### ISSUE THREAD

**Issue by SquidUlysses** [andstatus/andstatus#348]
I am unable to reply to messages through AndStatus.  Though the contextual menu appears, clicking on "Reply" only results in the creation of a draft message.  The message editor never appears.  Furthermore, attempting to edit the draft message also results in no action.  I've reproduced the problem with verbose logging enabled and have included only the logs generated while reproducing the problem.

**Comment by SquidUlysses** [comment]
[unable_to_reply.tar.gz](https://github.com/andstatus/andstatus/files/169660/unable_to_reply.tar.gz)

**Comment by yvolk** [comment]
During the log analysis I found out that in your local database you have two users with the same webfingerId ( orobouros@loadaverage.org ) and id in the GNU Social instance: 346451
One of this users is binded to your account ( id=155) and another (with internal id=331) - not. 
This situation confuses Application and it cannot find correct account in some cases, which causes misbehaviour.

These duplicating users should be merged, but AndStatus doesn't have such a tool yet...

The simplest way to solve this problem is to reinstall AndStatus.

```
2016-03-11-12-25-24 V/MyProvider: idToStringColumnValue table=user, column=webfinger_id, id=331 -> orobouros@loadaverage.org
2016-03-11-12-25-24 V/DataInserter: insertOrUpdateUser; Skipping partially defined: MbUser{oid=346451; originId=4; id=331}
2016-03-11-12-25-24 V/MyProvider: conditionToLongColumnValue; table='msg', column='sender_id' where 't._id=14549' -> 331
2016-03-11-12-25-24 ...MyAccount:{accountName:orobouros/LoadAverage,id:155,oid:346451,credentialsPresent,syncFrequency:900,syncable,syncauto}
```

**Comment by yvolk** [comment]
I implemented a procedure, which fixes such user duplication problem:
The fixing procedure starts automatically after completion of "Backup application data to SD card".
Available in AndStatus v.23.02+

**Comment by yvolk** [comment]
I used this "Check Users" procedure on my quite old database: and it found 4 users to merge.
What is still unknown: how Sqlite (database engine) allowed this duplication in the first place: database is created with a unique index on the duplicated field:
```
        execSQL(db, "CREATE UNIQUE INDEX idx_user_origin ON " + User.TABLE_NAME + " ("
                + User.ORIGIN_ID + ", "
                + User.USER_OID  
                + ")");
```

**Comment by SquidUlysses** [comment]
Sorry for the late reply, but I wanted to thank you for your help.  I'm using AndStatus daily now and like how far it's come.
