### ISSUE TITLE
Update Wiki with a User FAQ

### ISSUE THREAD

**Issue by Yowlen** [andstatus/andstatus#352]
I've noticed several issues labeled Q&A, but they're more like FAQ/troubleshooting references than actual discussions on an issue. Perhaps it would be better to put them in a section in the wiki & close those issues to save space and avoid confusion. There's a "developerfaq" page, so why not "User FAQ" & "Troubleshooting" pages, too? Some likely candidates for moving to the wiki:
#43 - How to connect via Proxy/Tor/Orbot
#225 - Where are AndStatus logs located?
#299 - Editing Online Posts
#295 - Why don't I see new posts in a Timeline?/Why isn't AndStatus syncing?

**Comment by yvolk** [comment]
AndStatus FAQ is here: 
https://github.com/andstatus/andstatus/issues?utf8=✓&q=label%3A"Questions+%26+Answers"

**Comment by Yowlen** [comment]
Yeah, I know. I was suggesting that it be moved to the wiki so that there's less open issues. It seems more organized to me that way. Up to you, though. If you don't wanna do it, feel free to close this. :)

**Comment by yvolk** [comment]
It's not about if I want to do this or not - this is about limited time and tasks prioritisation.
I will not close this ticket as this is not done. Maybe someone decide that this FAQ in Wiki is really important and do this... Anyway, FAQ should be updated periodically otherwise it may become misleading...

**Comment by yvolk** [comment]
The FAQ page created: https://github.com/andstatus/andstatus/wiki/FAQ
