### ISSUE TITLE
Option to start loading the beginning of the Timeline

### ISSUE THREAD

**Issue by moshpirit** [andstatus/andstatus#354]
Sometimes I disconnect AndStatus for several days and I have to keep loading the TL for a while till I get the latest messages. There's any way to reload it from news to last and keep an empty space to be manually downloaded? (Something like what Twidere does would be useful)

Thanks a lot in advance

**Comment by yvolk** [comment]
It's not that difficult, but it will require to make downloaded messages tracking more sophisticated including implementation of on demand downloading of older messages, what AndStatus never could.
Interesting task :-)

**Comment by yvolk** [comment]
Twitter API has "max_id" parameter to request older messages https://dev.twitter.com/rest/reference/get/statuses/home_timeline

**Comment by yvolk** [comment]
In order to simplify the solution I plan to do this:

Add an option "Don't synchronize old messages, if previous sync was more than ... hours ago". This mean that only on application start AndStatus will download newest messages (as it always does for a Public timeline in GNU Social). 
In a case you tap "Sync with Internet" several minutes later, AndStatus will not try to download "latest messages" again - it will request only messages, which were sent later than the last downloaded (i.e. it will request messages, which were sent later than previously downloaded), i.e. just like it does with "Don't synchronize old messages..." option turned off.
A User sets a value for this option in hours, i.e. "1" or "100" ... Empty value or "0" mean that the option is turned off.

**Comment by yvolk** [comment]
@moshpirit Implemented as I wrote above. Please test it, building from sources. Or I can upload apk for you...

**Comment by moshpirit** [comment]
Oh, I would appreciate the apk! Thanks a lot! :)

**Comment by yvolk** [comment]
Here it is.
Please note that if you are using FDroid-built package now, You should:
1. Make backup of your current data (Settings -> Storage -> Backup Application Data to SD card.
2. Uninstall old version
3. Install this package.
4. Restore data.
5. Test...

[AndStatus-26.00-release.zip](https://github.com/andstatus/andstatus/files/223124/AndStatus-26.00-release.zip)

**Comment by moshpirit** [comment]
The last version is beautiful!! Thank you! I'm testing now :)

**Comment by moshpirit** [comment]
What if I want to load just the last 30 minutes? maybe it should be loaded by number of messages; like the last 20 or 100 messages.

**Comment by bulletbites** [comment]
In _Syncing_, I set "Don't synchronize old messages, if..." to 48h. Seems to be a good average measure to avoid scrolling days up getting your TL refreshed to recent.

**Comment by moshpirit** [comment]
For people with several accounts who are following tons of people, in an hour AS might download more than 500 messages and that's a lot for a 3G traffic network on the phone. Selecting "Synchronize only the last ___ messages" (100 is a good number) may be a better option IMO.

**Comment by yvolk** [comment]
@moshpirit I don't know how to get a number of new messages since my last sync. This is why _time_ is the only reliable criteria.

**Comment by moshpirit** [comment]
I see.

BTW, I've just synchronized my TL after hours of no internet connection and it loads more messages than expected. (4+ hours ago with just last one hour synchronization top)

**Comment by yvolk** [comment]
It loads all latest messages. Up to 200 messages for GNU Social.
This means that you will gain anything from this feature only if you missed more than 200 messages since your previous "normal" syncing.

**Comment by moshpirit** [comment]
I've just installed the last version (26.3 from F-droid) and restored my backup where I only use Pump.io. I made it 6 days ago and I can't load anything new even if I select AS to sync the last 48 hours.

**Comment by yvolk** [comment]
@moshpirit I see. Anyway, I have to improve a way to clearly understand a state/progress of synchronization of accounts.

**Comment by yvolk** [comment]
Implemented in v.32
AndStatus now can download older messages of a Timeline. When a User have scrolled down to the oldest message of a timeline, the "Sync older messages" button is shown, which allows to request next page of older messages from a server. 
This may seem like a must have feature, but due to ability to store previously downloaded messages as long as a User wishes, it was not frequently requested. In fact, ability to view older messages may be needed mostly during the first day-two of AndStatus application usage, when there is not much data stored yet.

Note: This is not exactly what was described in the first messages of this discussion, but this is exactly what is written in the subject of this issue.
