### ISSUE TITLE
Notifications state being reset every day to that at installation. 

### ISSUE THREAD

**Issue by akwala** [andstatus/andstatus#398]
I repeatedly get notifications for DMs and Mentions as if the app were just installed. The numbers seem to reflect activity beginning on a date that is after account creation and the app appears to have seen the history for the first time in every notification despite clearing it every time. I OW, if there is no new activity since the last notification, I get the same notification as the previous.

**Comment by yvolk** [comment]
@akwala The question here is whether AndStatus repeatedly downloads the same DMs every day?
You can tell this using "Manage timelines" view.
Please go to "Manage timelines" and select "Reset counters" in its action menu. Next time, when you see new DMs mentioned, please see how many messages were downloaded by "Direct messages" timeline(s) ("Dnl." column) and how many new messages were among them ("New" count).
Please attach a screenshot of the "Manage timelines" list.

**Comment by akwala** [comment]
What I saw/did (in chronological order):
1. Got notification of 2 mentions.
2. Reset counters.
3 Got notification of 2 mentions the following day.
4. Took attached screenshot of Managed Timlelines (first row has the mentions in question).

Dnl = 12; New = 2 (Untitled column between Sync & Dnl = 6 -- what is this?)

The latest Mentions are two on the same date. Incidentally, I did a reinstall of the app recently during which I added my accounts anew, and I got the initial notifications of all past mentions/DMs as expected. The repeating notifications have been happening since then.

I verified that both notifications above referred to the same mentions by taking a screenshot of the messages after each notification and comparing them.

I tracked Mentions because I rarely get DMs :( 

![screenshot_20160920-100615](https://cloud.githubusercontent.com/assets/1786/18676874/1b59dc04-7f25-11e6-9dfc-3cd0d8086b25.png)

**Comment by yvolk** [comment]
@akwala The untitled column between Sync and Dnl. shows a number of successful syncs since your last "Reset Counters”.
If you see the counters "since yesterday", this could mean that you have automatic sync every 4 hours.

The table also shows that two of 12 downnloaded messages in the first timeline were considered as new, and this is why you've got a notification of 2 new mentions in this case.
Please note that counting messages for notifications (not in this Manage Timelines table) was implemented long time ago and needs revisiting and reimplementation. See https://github.com/andstatus/andstatus/issues/367

**Comment by yvolk** [comment]
AndStatus has new "Unread Notifications" timeline since v.45 (January 2019).
That Timeline clearly shows, when each note was downloaded. And activities in that timeline are sorted by download time, and not by the activities' publish/create time...
