### ISSUE TITLE
Timeline don't show messages sent via GNU social web

### ISSUE THREAD

**Issue by kai11** [andstatus/andstatus#404]
1) reinstall AndStatus
2) create GNU social account
3) add few messages to GNU social via Web interface
4) sync with internet

Expected result
1) displayed messages from web

Actual result
1) only local messages displayed (updated, not drafts)

P.S. This problem appear within last few releases.

**Comment by yvolk** [comment]
@kai11 I see where possible problem could be:
After your step 2 AndStatus does sync for the first time. And you should see existing messages in a timeline after this step. Please check, which messages are loaded right after step 2.

After your step 4 AndStatus probably makes sync "since step 2", and this is why only new messages are loaded.

Currently AndStatus cannot sync "older" messages. This will be implemented in https://github.com/andstatus/andstatus/issues/354 "Option to start loading the beginning of the Timeline"
