### ISSUE TITLE
AndStatus crashes when adding new Twitter account

### ISSUE THREAD

**Issue by HandyGeek** [andstatus/andstatus#406]
Just loaded AndStatus on Samsung S5
When I try to add the first Twitter account AndStatus crashes as soon as I type the first letter of the account
I don't have any other accounts in AndStatus
In case it may be relevant (some sort of conflict) - Plume is loaded - I was testing to see about switching to AndStatus

**Comment by yvolk** [comment]
@HandyGeek Please send a Crash report to me.
Do I understand correctly that you "type the first letter of the account" in a Web view of a twitter.com site: ”Authorize AndStatus to use your account" page?

**Comment by junes** [comment]
Same here on S5 mini: when I enter the 1st letter of my username in text field "AndStatus-OpenSource berechtigen, Deinen Account zu nutzen?" AndStatus crashes.

**Comment by yvolk** [comment]
@junes @HandyGeek Any info on the crash? Could you send me a Crash report?
Meanwhile try to install AndStatus from Google Play https://play.google.com/store/apps/details?id=org.andstatus.app

**Comment by HandyGeek** [comment]
Yes

**Comment by HandyGeek** [comment]
It is already instslled. When I go to google play it sees that it's already 
installed.
I will try to get & send a crash report a little kater.
Thanks

**Comment by HandyGeek** [comment]
Was just able to add an account but after testing I tried to add a second 
Twitter account & it crashed.

**Comment by yvolk** [comment]
@HandyGeek I cannot reproduce the problem. I just added Twitter account successfully on both Nexus One with Android 4.4 and on Sony XPeria 1 with Android 6...
Please, help me to fix this problem and answer these questions:
Q1. Any info on the crash? - Write as much as you can about how the "crash" looks.
Q2. Could you send me a Crash report?
Q3. Does changing from f-droid distribution to Google Play one makes any difference?

**Comment by junes** [comment]
Please see the attached screen shots. (Sorry, but I don't know how to create a crash report and where to find it. I have enabled debug and safe to file, but I cannot find the file.)
On my phone the problem only occurs when I try to add a second twitter account. 
I will try to change the distribution from Fdroid to Play and report back.
![image-403870232](https://cloud.githubusercontent.com/assets/3236206/17587193/f1f50cee-5fc6-11e6-835b-46160b5c37e3.jpg)
![image-1131800254](https://cloud.githubusercontent.com/assets/3236206/17587201/02fc173a-5fc7-11e6-86c9-3d36ccf16437.jpg)

**Comment by HandyGeek** [comment]
Do I have to delete then reinstall to test the Play version? I'm not sure 
what changed but without doing anything at my end but it stopped crashing 
when the first account is entered but I'm getting the same second account 
crash as the other user is reporting. Where is the crash report stored? Or 
at least what is the name or extension, please?

**Comment by yvolk** [comment]
@junes  On AndStatus logs location please read https://github.com/andstatus/andstatus/issues/225
It would be very handy to see the error stack trace in logs...
The prompt to send me a crash report should popup automatically. As I see, it doesn't appear in your case, for some reason...
Yes, in order to install Google Play package you have to uninstall any other first (they have different signatures). Reinstallation may help in any case...

**Comment by yvolk** [comment]
We could reproduce the problem, thank you!
The problem is in some incompatibility with Android embedded Web view, used by AndStatus:.
As now I can reproduce this, I can start fixing the problem.

**Comment by yvolk** [comment]
Thank you all, the problem is fixed. It will be present in the next release.
It looks like the problem was present for a long, but you guys, including @hikerus, were the first, who could communicate it to developers. Thank you again for your patience!

Regarding possible **workaround until the fix is released** I can think only about these:
Option 1:
1. Reinstall AndStatus and don't make any mistakes during account creation (looks like crashes start after the first failure, persist even after reboot... unbelieveable).
Option 2:
1. Create backup of your data in AndStatus settings -> Storage
2. Reinstall AndStatus
3. Restore backup on the first AndStatus launch
4. Add (another) account.

**Comment by HandyGeek** [comment]
Awesome! Thanks for the good news ... Standing by for the new release ...

**Comment by yvolk** [comment]
AndStatus v.27.05 released with the latest fixes

**Comment by HandyGeek** [comment]
Is the newest release current on both fdroid & play store, please? I try to 
set all updates manual. Thanks!

**Comment by yvolk** [comment]
AndStatus v.27.05 is currently available via Google Play only at https://play.google.com/store/apps/details?id=org.andstatus.app
F-droid team makes releases according to their own schedule (more on this https://github.com/andstatus/andstatus/issues/326 ), I don't see the new version in their repository yet.

**Comment by HandyGeek** [comment]
I just emailed a request that they post it asap.

Perhaps enough people asking & they'll make it so.

Any way to avoid contact with google is worth the extra effort.

Thanks - David

Quoting Yuri Volkov <notifications@github.com>:

**Comment by junes** [comment]
From my side we can close the ticket. I have received the update via Fdroid. All is fine now. Second Twitter account is working. Thank you very much!
