### ISSUE TITLE
[Twitter] Twitter blocks AndStatus from F-Droid - results in "Forbidden" - Messages remain unsent (occasionally?)

### ISSUE THREAD

**Issue by schumaml** [andstatus/andstatus#415]
Hi, occasionally I got messages that remain unsent forever for my Twitter account, despite multiple attempts to resend them. It doesn't matter whether they are replies or new messages.

I've read https://github.com/andstatus/andstatus/issues/295 and check the commands in queue log, and see that there was a HTTP status error "Forbidden".

I could share the log entry, but have two questions:

1. Does this log contain anything I shouldn't share (e.g. some authorization token, ...)?
2. How do I actually share a log entry there? Can't find any way to do this, despite the link mentioned above stating this possibility.

**Comment by yvolk** [comment]
I was getting similar Forbidden error some time ago, see 
https://mobile.twitter.com/AndStatus1/status/750563256834613250
I edited the same post several times in AndStatus and at last it was accepted. 
I didn't figure out what exactly caused this error.
-- 
andstatus@loadaverage.org
 URL: https://loadaverage.org/notice/8458361

**Comment by schumaml** [comment]
I can't find any pattern in the messages that remain unsent. Long, short, quotes, no quotes, replies, new messages, ...

**Comment by yvolk** [comment]
@schumaml How many tweets did you send successfully via AndStatus, and how many couldn't be sent due to this ”Forbidden” error?
For me this statistics is about 10 to 1 unsent.

**Comment by EricxDu** [comment]
Didn't realize this issue was related to mine. Okay so afaik NONE of my replies or retweets (possibly favorites and posts as well) are making it to Twitter. They are being blocked by a Forbidden error, as seen in Commands In A Queue. I will try to send a few more replies in the near future to help continue this investigation.

**Comment by schumaml** [comment]
The issue seems to get worse - I think all messages I try to send from one of my devices run into this issue now.

**Comment by yvolk** [comment]
I just tested to post to Twitter using Google Play distribution package: no problem https://mobile.twitter.com/AndStatus1/status/780638309542395904
It looks like Twitter started to ban ”AndStatus-open source” application, registered at Twitter specially for the publicly available source code. The problem is that in order to be built by f-droid or by any individual developer without any "Application registration" at Twitter the code has to include key information that shouldn't be easily available...
For Google Play distribution I use another keys, belonging to another registration at Twitter. And I keep that keys private. I guess this is why I still can post to Twitter.

As an immediate workaround please 
1. backup your f-droid distributed AndStatus application, 
2. Uninstall it
3. Install AndStatus from Google Play
4. Restore your data from the backup.
5. Re-verify your Twitter accounts from inside AndStatus.

You can tell, which AndStatus distribution package you are currently using by looking up its screen with a version number (Help -> Learn more...)
Google Play version says (release-keys) and f-droid one, naturally: ”f-droid-keys”. See #407

In the long run I will add an option for a User to set any "Twitter application" keys , but this will mean that the User will have to get these keys from Twitter himself...
As you may know,

**Comment by schumaml** [comment]
It's not simply running into some overall API key posting limits, is it?

**Comment by yvolk** [comment]
Yes, logging into Twitter I see that AndStatus is "Restricted from performing write actions”.
See https://support.twitter.com/articles/72585
![andstatus-restricted](https://cloud.githubusercontent.com/assets/207716/18882724/1d54f5f6-84e9-11e6-838f-7d132ad384c2.jpg)

**Comment by yvolk** [comment]
Almost immediately I got a reply that the restriction is lifted: "We have reviewed your request and have reactivated your API key. Going forward, carefully ensure that your application adheres to Twitter’s policies..."

**Comment by EricxDu** [comment]
I wonder what policies AndStatus-opensource might have run afoul of.

It seems to me for a couple of reasons this problem or similar could occur in the future

**Comment by yvolk** [comment]
@EricxDu I suspect so, so I wrote another request for clarifications and advises for my way to avoid repetition of the problem.
I suspect that somebody used Open Source code of AndStatus or/and its impersonation in Twitter in some wrong way...

**Comment by EricxDu** [comment]
BTW I have not yet confirmed that AndStatus on my phone is fully working with Twitter again.

On September 27, 2016 12:04:50 PM PDT, Yuri Volkov <notifications@github.com> wrote:
>@EricxDu I suspect so, so I wrote another request for clarifications
>and advises for my way to avoid repetition of the problem.
>I suspect that somebody used Open Source code of AndStatus or/and its
>impersonation in Twitter in some wrong way...
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/andstatus/andstatus/issues/415#issuecomment-249965349

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by yvolk** [comment]
I received this rely from Twitter support. It tells about a mistake of an automated systems, but I think that they simply check if "Twitter application" owners are alive and turn off abandoned applications periodically... 
```
Hello @AndStatus1, 

Twitter has automated systems that find and disable abusive API keys in bulk. Unfortunately, it looks like your application got caught up in one of these spam groups by mistake. We have reactivated the API key and we apologize for the inconvenience. 

Regards,
Twitter Platform Operations
```

**Comment by schumaml** [comment]
Confirming successful send of any unsent message from my phone.

**Comment by EricxDu** [comment]
I've had little chance to test Twitter due to a couple of other bugs (I should probably report soon), but I just did a test reply on an old post which showed up at twitter.com as expected. So: fixed here!

In case it *is* related, I haven't been able to refresh my Twitter feed in AndStatus, even after this fix. Some tweets show up (ones that I've posted recently and replies to me), but regular timeline posts don't refresh.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by yvolk** [comment]
@EricxDu On problems with syncing we have a separate Q&A https://github.com/andstatus/andstatus/issues/295
