### ISSUE TITLE
Will not post replies to Pump.io

### ISSUE THREAD

**Issue by EricxDu** [andstatus/andstatus#420]
I've been sending replies to messages on a Pump.io node. The replies appear in timelines in AndStatus, but they never actually appear in the Pump.io network.

Not much data to go on yet. Doesn't appear in 'commands in a queue' because AndStatus seems to think it sent.

**Comment by yvolk** [comment]
Please try "Open on Internet" context menu item for the reply that you don't see in the Web UI.
If above didn't help, post more details with concrete URLs here.

**Comment by jankusanagi** [comment]
> The replies appear in timelines in AndStatus, but they never actually appear in the Pump.io network.

Do you have an example URL of a post where you replied and your reply is not showing? It might have been a case of replying to a comment instead of the parent post. That would make the comment-to-a-comment difficult to see in some cases, including the web interface.

**Comment by EricxDu** [comment]
Yes, I just found an example.

Link to a post from AndStatus: https://1realtime.net/EricxDu/comment/SHnicrauQmWQgTRq-XntsA

Conversation I expected to see the post in: https://1realtime.net/EricxDu/note/d_cG8SbtR6WcsyuG0KyJKQ

**Comment by jankusanagi** [comment]
Same examples I posted ;)

This isn't really a bug. The problem here is that AndStatus is primarily a microblogging client, so it expects users to reply to comments directly with another comment, instead of replying to the parent post, which works best **currently** in Pump.io, mainly because some clients, mainly the web interface, don't show threaded conversations correctly.

But as you can see, your comment is there. And the user was notified of it. I don't know if you have an easy way to "go back" to the original post, but you should simply reply to that.

Maybe AndStatus could make this option easier.

**Comment by EricxDu** [comment]
Okay thanks. It's not difficult for me to reply to the parent post. I must have started to change my habits recently.

As this does not seem solvable from AndStatus at all, I will close the bug.

**Comment by yvolk** [comment]
I hope other Pump.io clients, including Web client, will be expanded to show comments on comments.
As I wrote three years ago and can repeat today: current Web interface of Pump.io looks more like a Proof of concept with teasers of what it could be rather than like a released application...

**Comment by EricxDu** [comment]
That is pretty much what the web client is, from everything I've read since the beginning of Pumpio. It was meant to showcase the basic features and encourage app developers to make other things.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
