### ISSUE TITLE
How to connect via proxy / Tor / Orbot

### ISSUE THREAD

**Issue by yvolk** [andstatus/andstatus#43]
Investigate if AndStatus can be connected via proxy, e.g. via orbot https://guardianproject.info/apps/orbot/

Possible implementation:
1. Short search shows this solution for apache.http.client: http://stackoverflow.com/questions/12314361/https-over-a-proxy-with-apache-http-client
2. java.net.HttpURLConnection documentation http://developer.android.com/reference/java/net/HttpURLConnection.html also has notes information on connection via proxy.

**Comment by amunizp** [comment]
Hi just revisiting this after a very long time. I di not understand what you need me to do. I have tor app working with fennec and duckduckgo. How can I help?

**Comment by yvolk** [comment]
@amunizp I thought that maybe "tor" has an instruction how to connect via it for any application. So you could try if AndStatus can be configured for this?!

**Comment by vinzv** [comment]
Here are generic instructions for Orbot: https://www.torproject.org/docs/android.html.en
So I assume you'll need to point Andstatus to HTTP port 8118 or SOCKS port 9050 on localhost
IP 127.0.0.1.

**Comment by amunizp** [comment]
So sorry for dumbing this down for me. 
 In my particular example I use gnusocial with loadaverage and orbot I would need to put in server (node field) the following:

 https://username@loadaverage.org:password@loadaverage.org:127.0.0.1:8118

The IP address seems kinda forced in there but I did not know where else to put it.
But anyway, would this not mean that my username/password will be going out in the clear?

**Comment by yvolk** [comment]
I saw the Tweet:
```
[Tweet from torrified AndStatus]
```
https://twitter.com/akater/status/657141850512445440

And on my question of how this was done the User answered:
"Nothilng sophisticated, I'm using standard Android VPN feature for now (available in a recent Orbot)... I posted it to check if I could tweet from Tor this way (Web interface wouldn't allow me anymore.) Didn't even bother to analyze outcoming traffic. Messages don't load wiith Orbot turned off, so I guess it works as intended."

**Comment by maste9** [comment]
Also like to tor my networking. I tried to alter the quitter.se settings from quitter.se to quitter.se:localhost:8118
Unfortunately this doesn't make any use of the orbot proxy (which is validated by successfully proxying Twidere). 
I'm not experienced in app development so be allowed my naive question: 
Is it a big thing to add an option regarding proxy in settings and to route all the AndStatus traffic through it? Which would make it such convenient to use tor so that it would be a full alternative to Twidere, that does not allow searching in anything than Twitter.

**Comment by yvolk** [comment]
@maste9 I didn't try this either, so I hope that one day someone will take a time to give us step-by-step instruction for this. 
Then I will figure out how the settings could be simplified inside AndStatus.

**Comment by akater** [comment]
User AndStatus1 at twitter.com asked me to comment on the Torrified setup in detail: https://twitter.com/AndStatus1/status/657432791458672640 and I promised to. Here it goes:

Since not-so-long-ago, Orbot offers routing arbitrary applications' traffic via what is described as «built-in Android VPN support», whatever that means. Tutorial for dummies is as is: in Settings for Orbot, tap «Select Apps (Choose Apps to Route Through Tor)», check AndStatus (which has to be installed at the moment, of course). Restart Orbot (it's probably neccessary, and Orbot warns about it every time).

It doesn't require root. It's aimed at end users. I have no idea how it handles DNS. It's not the same as Orbot's Transparent proxy functionality. It doesn't allow to specify proxy port (say, for purposes like stream isolation) and in general doesn't seem to be configurable above what I described. It's possible that this setup always works as desired (my personal experience suggests it does) but I haven't yet figured out what built-in VPN support really is, mostly due to lack of time.

Related guardianproject's follow-up tweet on how to implement Tor support natively: https://twitter.com/guardianproject/status/657490337091448832

**Comment by moshpirit** [comment]
I did it with all my apps, but does it work if you don't use a rooted phone?

**Comment by akater** [comment]
I can't remember for sure but it probably doesn't. Related: https://android.stackexchange.com/questions/98321/why-does-orbot-need-root-for-transparent-proxying-but-openvpn-doesnt

**Comment by yvolk** [comment]
Tip from a user:

@andstatus i can torify your app. The tip is to put the proxy 127.0.0.1:8118 in APN and WIFI options

 https://loadaverage.org/notice/7558210

**Comment by mathiasfriman** [comment]
I would like to use AndStatus with i2p, which means using Orbot does not work. 

I need to proxy via **localhost:4444**, how should I write this if my GNU Social site is at **gnusocial.i2p** with user: **testuser** and password **testpass** ?
