### ISSUE TITLE
Start a direct message creation and select a recipient

### ISSUE THREAD

**Issue by mama21mama** [andstatus/andstatus#438]
I am very difficult to interface to send direct messages. It is possible in the future to improve this function. I do not want to send a direct message to follow a conversation. I want to start a direct message. The interface is complicated. Everything else is excellent. only that.

**Comment by yvolk** [comment]
Currently in order to send a direct message to a User you have to:
1. Option 1. Find one of his/her messages and select "Direct message" in the context menu.
You can e.g. switch to "Friends" timeline, where each of your friends is represented with exactly one message, and find a friend to write to there...

2. This option is not implemented, but it's easy - I just need to add a menu item: Option 2. Find a message, where this User is either an author or simply is mentioned, select "Users of message" in the Context menu. You will see a list of Users. Tap a User and select "Direct message".

Is that not good?

Do you mean that you need to start creation of a Direct Message by searching for a User in a separate list?! Anyway, that should be list of Friends, as I understand?!

**Comment by yvolk** [comment]
"Direct Message" context menu item added to a User List. This means that now you can send a Direct Message to any user, mentioned in a Message, via "Users of message" list.

Available since v.32.01
