### ISSUE TITLE
Can't make combined timeline default

### ISSUE THREAD

**Issue by akater** [andstatus/andstatus#454]
I disabled or turned off combined a long time ago.

Now can't make combined timeline default (it was turned off till I was using Twitter only). Settings › Timeline doesn't contain “Timeline is Combined by default” as ChangeLog 2016-04-14 v.25.04 (171) suggests.

Not sure if unrelated to #453, all this could be due to my particular non-default settings state not making it through AndStatus updates.

**Comment by yvolk** [comment]
In order to make ANY Timeline the Default ​timeline:
1. Switch to the Timeline that you want to be default. This can be any timeline, even Search timeline.
2. Tap "menu overflow" button (three vertically placed dots) and Select "Manage Timelines" menu item.
3. "Manage timelines" table opens, which lists all timelines, to which you ever switched. Rows may be sorted by any column (just tap on a column header).
4. Scroll to the Timeline that you chose on step 1 and tap on its title.
5. Context menu opens. It has "Default timeline" item.
6. Tap the "Default timeline" item.
See the small "D" letter to the left of the Timeline's title - this means that now it is the Default timeline.
![screenshot_20170421-191115](https://cloud.githubusercontent.com/assets/207716/25286509/b2f399a8-26c6-11e7-8545-64534ac675b4.png)

**Comment by akater** [comment]
Indeed, combined timelines are there. Thank you.

I noticed the timelines table but did not notice combined timelines' rows. For anyone interested --- they are below all the search timelines in my case.
