### ISSUE TITLE
Follow in GNU social by UID (username@domain)

### ISSUE THREAD

**Issue by akater** [andstatus/andstatus#455]
As far as I can see, there is no way to follow an entity by typing in its username@domain identifier.

GNU social web interfaces also lack this feature, apparently. Most I could do was visit the said entity's webpage while logged in to a GNU social instance, click some button, follow the redirect link.

A more straightforward and universal mechanism would be welcome.

**Comment by akater** [comment]
One way to follow via web in my case is https://loadaverage.org/main/ostatussub?profile=username@domain

Might be specific to LoadAverage web UI though.

**Comment by yvolk** [comment]
Since v.35 you can Search for a User, typing only some letters of their name. Check "Search in Internet" to search for users not only in the local cache (works for Mastodon and Twitter only).
User List opens, where you can select a User and follow him.
![scr-search-users](https://user-images.githubusercontent.com/207716/28687885-a88cec3c-7318-11e7-9e0c-663d4cca8c6d.png)

**Comment by yvolk** [comment]
I checked GNU Social API (and even its Source Code https://git.gnu.io/gnu/gnu-social/blob/master/actions/apifriendshipscreate.php ) and it looks like there is no means to follow a User by a WebfingerId ( user@domain ), only by numeric ID and a local username ( without domain ).
Moreover, there is no User search available (which could allow to search for a user first and then follow him).
So closing this ticket as cannot be done.
