### ISSUE TITLE
v35.05 feels very sluggish

### ISSUE THREAD

**Issue by schumaml** [andstatus/andstatus#468]
On my phone, a Galaxy S5 Mini, v35.05 feels very sluggish.

Takes several seconds to show up when started, and switching timelines takes even longer to display anything.

Is there anyrhing I can try to make this faster?

**Comment by yvolk** [comment]
Startup really may feel longer, because currently some of initialization tasks are done before opening the first activity. Actually, I added this in v.34.05

Large amount of data stored is the main cause of the slow work. So decreasing number of days to store data will help. On my 3 years old device I have about 250 000 messages and I understand your words about being sluggish... but so far _I_ prefered to wait and don't delete old data...

Large number of timelines could be another cause of a long startup, could you look up "Manage Timelines" table? I need to add some purging of unused timelines...

Currently I'm doing quite radical internal data re-design in AndStatus, so in AndStatus v.36 we will see different behaviour. Hope not to decrease its responsiveness...

**Comment by schumaml** [comment]
I've erased my Twitter account from Andstatus, and re-added it. I hope this actually removed anything related to the account and provided me with a clean slate.

Same sluggishness. 

I'm starting to chalk this up as "Galaxy S5 mini is simply not powerful enough to run Andstatus comfortably" for now. Currently evaluating Twidere,

**Comment by yvolk** [comment]
@schumaml No, deleting an account doesn't delete anything from a local cache.

**Comment by schumaml** [comment]
Hm.... the wording of the corresponding message - "remove all its data" - suggests it would.

So is there a way to get rid of all the data, as if an account had never been there?

**Comment by yvolk** [comment]
Android account and its data are removed, but local cache (messages and users) of AndStatus does not belong to any _one_ account: it's shared between them. I.e. all accounts in one Social network share the same messages.
On the other hand, AndStatus has automatic purging procedure, which deletes old messages and attachments. See Settings -> Storage -> History Time / Size

**Comment by yvolk** [comment]
@schumaml What's about v.36.05 ? 
See https://github.com/andstatus/andstatus/issues/456

**Comment by yvolk** [comment]
@schumaml In v.36.08 I specifically paid attention to the smoothness of scrolling, and found some places, which cause slow downs, see https://github.com/andstatus/andstatus/issues/478
Please try and see the difference!
