### ISSUE TITLE
How to specify nonstandard port for node server. 

### ISSUE THREAD

**Issue by jbonomi** [andstatus/andstatus#485]
I run a Friendica node that uses port 8081, but there's no way to configure this in AndStatus. If I append :8081 to the server URL I cannot add it.

**Comment by yvolk** [comment]
Actually entering full URL of the server root folder into the "Host" field is supported for a long time, see https://github.com/andstatus/andstatus/issues/116#issuecomment-54778645
The problem is that this (advanced) feature is not documented in the application's UI. Even a "hint" of the "Host" field doesn't mention such an option, only simple host names:
![screenshot_20180510-135259](https://user-images.githubusercontent.com/207716/39866536-c29a6730-5459-11e8-9155-a1847ca70ec1.png)
