### ISSUE TITLE
[GNU social] Third Party Developer Interfaces

### ISSUE THREAD

**Issue by t3nma** [andstatus/andstatus#504]
As part of GSOC 2019 I'm writing a proposal for the GNU social's idea [Review third party developer interfaces](https://www.diogo.site/projects/GNU-social/soc/2019/).

The current API uses OAuth1 for handling clients and some discussion arose regarding the different alternatives I can take as for the integration of Bots in the system. As I will detail below, the drop of OAuth1 (aka change in client support) is being considered and therefore I came here seeking for the third-party community thoughts on the different strategies:

1. A first and very straightforward solution is to introduce OAuth2 for Bots while maintaining OAuth1 and its support for clients. This would maintain backwards compatibility and the current Twitter-like API (their authentication model is also using both OAuth versions).

2. There is no particular reason (other than compatibility) as for not providing TLS and fully adopt OAuth2, so another obvious solution to consider is to fully replace OAuth1.

3. Introducing LitePub, dropping OAuth (again). I must say I wasn't familiar with this protocol/standard until it came up in this matter discussion at freenode/#social. It seems this would be a great solution for heading towards good API compatibility between different federated software. On another hand, it would require signatures and that is just like maintaining one of the not so good aspects of OAuth1.

**Comment by yvolk** [comment]
Hello @brunoccast. 
As you may know, I'm developing the AndStatus application, that supports GNU Social since November 2013, when it was StatusNet yet (see http://andstatus.org/changelog.html ).
I could never implement OAuth for StatusNet, because the was no single working example available. So since that time AndStatus connects to GNU Social via Basic Auth only.
Meanwhile OAuth 1 works fine with Pump.io since September 2013 (i.e. even before StatusNet).
AndStatus does have working support for OAuth 2 also: it works with Mastodon since June 2017 and, what's more interesting, it is being in active testing and extended development for ActivityPub Client-to-Server API, see https://github.com/andstatus/andstatus/issues/499

Switching to OAuth 2 for GNU Social is an easy task for AndStatus.

So my conclusion is that the best way for GNU Social would be full adoption of OAuth 2, creating implementation that will serve for ActivityPub clients also! Please read and take part in the discussion https://github.com/andstatus/andstatus/issues/499 keeping in mind this compatibility aspect. It has much info on OAuth 2.

**Comment by brunoccast** [comment]
Hello @yvolk , thanks for your answer.

I didn't say it, but the full adoption of OAuth 2 was already the "strongest" candidate, so its good to see some agreement. I don't  understood something though. When you say 

> ... full adoption of OAuth 2, creating implementation that will serve for ActivityPub clients also

does this mean you think its best to maintain the current twitter-like API and also implement the AP C2S API? If so, I don't understand the benefits of it.. Is it, perhaps, just planning for future implementation compatibility with all software?

**Comment by yvolk** [comment]
@brunoccast As I see, there are different concrete options to implement OAuth 2. Each option require some specific configuration, maybe even different algorithms used... (see e.g. ScribeJava library with tens of configurations...) I think that while selecting concrete OAuth configuration for current Twitter-like API of GNU Social, it would be good to choose the one that will work (with minimum changes) for OAuth steps of the future ActivityPub implementation.
- Just to save some future development and migration efforts.
The discussion that I linked to show how not easy is to adapt existing "OAuth2" to ActivityPub.

**Comment by brunoccast** [comment]
Understood @yvolk, thanks again.
