### ISSUE TITLE
Support for Mastodon custom emojis?

### ISSUE THREAD

**Issue by chillgamesh** [andstatus/andstatus#516]
Is there planned integration to show masto instances' local emojis inline and be able to post with them?

**Comment by yvolk** [comment]
I didn't think about this yet... Just looked up https://emojos.in/mastodon.social
Want to implement this?

**Comment by chillgamesh** [comment]
Looks like that's only the set from mastodon.social. Is there a way to grab custom emojis from each instance? Or even as a start, the instance that a user has their account on?

**Comment by yvolk** [comment]
As I understand, if you manage to configure custom emojis in AndStatus somehow, only you will see them this way. Other users, including your friends will see other emojis in the same messages (or no emojis at all, like in AndStatus now).
?!

**Comment by kobitate** [comment]
[As documented here](https://docs.joinmastodon.org/methods/custom_emojis/), Mastodon instances can include their own list of custom emoji. When AndStatus receives a Mastodon post or profile text with a custom emoji, it shows as the emoji's slug as defined by the instance owners. AndStatus does not currently support showing these emoji. For example:

![telegram-cloud-photo-size-1-5037731922649918290-y](https://user-images.githubusercontent.com/2555575/211630227-3f5d9e05-cf10-4067-8eed-f91a7f54256a.jpg)

These slugs can be translated to the proper image URL using the Mastodon API `GET /api/v1/custom_emojis`. Here's how my profile renders on the official Mastodon client:

![telegram-cloud-photo-size-1-5037731922649918291-y](https://user-images.githubusercontent.com/2555575/211630935-f3c464d1-c420-46dc-88e0-257e407b9fd1.jpg)

Custom emoji support would be a great addition to AndStatus -- considering reopening this ticket and implementing custom emote support. I am considering implementing but I am not super well-versed in Kotlin.

**Comment by yvolk** [comment]
Hi @kobitate!
Is absence of custom emojis the most annoying AndStatus problem for you?

**Comment by kobitate** [comment]
Yes, I'm on an instance with a lot of custom emoji. When posts come across my feed they're often missing the emoji for users on the same instance.

**Comment by yvolk** [comment]
> I am considering implementing but I am not super well-versed in Kotlin.

Reading this thread again I see that turning this feature on will mean that:
1. AndStatus will have to download a separate set of images plus mappings from emoji codes to these images for each Mastodon instance, actors (users) or notes (posts, actions...) from which are present in the local app cache (present in some of timelines...). We need new data tables etc. to store them, ability to view and choose them in some screen...
2. For viewing each note should be transformed (emoji codes replaced with images) according to this note's origin's (instance, where it was created) set of emojis. So notes having the same emoji codes but created at different servers will look different in the same AndStatus timeline.
3. Currently text of a note cannot show images inside it. We need to learn how to start showing images inlined in text. Probably this is the easiest part...
4. We may expect performance degradation, not so smooth timeline scrolling due to above complexities.

**Comment by yvolk** [comment]
@kobitate Regarding Kotlin in AndStatus.
AndStatus is being developed since 2009, and only in 2021 it was converted to Kotlin. So most of its code still looks very like Java :-)
I want to encourage you to implement this feature, but note that the main difficulty is not in coding, but in figuring out, where to make changes in existing code for each part of the change.
And above 4 points are only a part of what really needs to be changed/added to make this feature live.
