### ISSUE TITLE
Video playing support

### ISSUE THREAD

**Issue by karnotcycle** [andstatus/andstatus#536]
Why doesn't videos or gifs play in Andstatus timeline?. Is there something I need to turn on?.

Apart from this. Amazing project! Love it so much. I will be contributing to maybe documentation and stuff soon. Personally I think it can be way better than twidere.

**Comment by yvolk** [comment]
Hi @karnotcycle,
Thank you for the AndStatus project review,

1. Regarding animated GIFs support: it works in a timeline, but animated GIFs, as it appears, are mostly not supported by social networks,  please see: https://github.com/andstatus/andstatus/issues/330
2. Video preview is shown in AndStatus. You have to click on it to launch external video player: the one that you have to choose and install on  your device. Does this work for you?

**Comment by karnotcycle** [comment]
I am extremely sorry, I had the notion carried on from an older version. It's been a while since I used the new one. I just went through everything last night. Most of the problems are fixed plus there are some new features too.

Sorry, I didn't mean to be mean. Pardon my ignorance.

**Comment by yvolk** [comment]
@karnotcycle Thank you for feedback. Glad that you like the app. Maybe you could also share your experience in Google Play or the Net... ;-)

**Comment by karnotcycle** [comment]
Hey, sorry but I didn't know where else to reach you. I want to ask what is the motivation behind naming the app andstatus? What's it mean? I know it maybe a stupid question. Feel free to ignore. But I'd like to know if you don't mind it... :)

**Comment by yvolk** [comment]
@karnotcycle  Thank you for asking :-)
Back in 2009 I joined development of "AndTweet" app.  The app supported only Twitter at that time hence the name, I guess.
In 2010 I became the main developer of the app. 
In 2011 Twitter announced a list of its own words, forbidden to be used in names of other developers' apps... and the "tweet" word was among them.
This is why I had to rename the app. I made minimal change: "Status" is used in the new name as a synonym of "Tweet".
Since that time AndStatus was literally re-written several times, and now it supports several social networks, Twitter not being the most popular by AndStatus users anymore. So the new name fits it much better.

**Comment by karnotcycle** [comment]
Thank you for the answer. I don't really use playstore, but I have got most of my friends over to andstatus by showing them how amazing it is. Thank you for such a great app. I love the concept of it.
I would like to discuss about the UI and help make it even better, if you could point me to its open issue it'd be great.

I am coming from tusky. I never thought I will like andstatus, seriously the recent installation was just to see where the project is going. But for some unfathomable reason I am in love with it. I am finding it hard to go back to tusky or twidere. :)

**Comment by yvolk** [comment]
@karnotcycle I'm open to UI improvements, thank you for offering your help in identifying and making such improvements.
In order to be achievable, such improvements should be as small as it is practical.
Please note that the app has a lot of UI tweaks in its Settings. Play with them, and maybe something is already done, but hidden or not advertised properly...
Next please select improvement that you feel would be the most important for you, and create an issue here in GitHub (start with searching of an existing one...), so we could discuss it.

Waiting for your feedback!
