### ISSUE TITLE
Be able to insert line feed (enter) without sending message. - Feature Request

### ISSUE THREAD

**Issue by rimugu** [andstatus/andstatus#550]
It would be nice if we were able to insert line feed (enter) without sending message.

**Comment by yvolk** [comment]
@rimugu Please try to turn on Settings -> Gestures -> "Show Send button near the composed note" - that button could be used to send notes.
Please see this discussion https://github.com/andstatus/andstatus/issues/533

Anyway, Enter/line feed soft button shouldn't send a note (message). 
But maybe you didn't update AndStatus for a long time? Current version is 59.05 for Android 7+

**Comment by rimugu** [comment]
I tied that before, just tried again, keyboard (AnySoftKeyboard) sends the message even when gesture enabled.
Version 2021-09-30 v.5905 (349) from f-droid.org

**Comment by yvolk** [comment]
So looks like this problem is specific to the keyboard app.
In this case I think that the keyboard app could have some settings regarding its "Action key". The "Action key" should insert a new line into the text box, and not cause an action launch.

Could you post screenshot at the time, when you are typing a note, with the text box and a keyboard visible.

**Comment by rimugu** [comment]
You are totally right, it is the keyboard not AndStatus. My bad, sorry.
