### ISSUE TITLE
Misskey Support

### ISSUE THREAD

**Issue by 4ioskd** [andstatus/andstatus#554]
Hello, I'm Dignified Silence. Misskey Contributor.

Do you have a plan to make andstatus work as a client app for Misskey?
Misskey is one of fediverse software which has rich features and a flexible UI.

Misskey Official Website: https://misskey-hub.net/
Misskey API Documentation on its Official Website: https://misskey-hub.net/en/docs/api
Misskey API Documentation in Misskey instance: https://misskey.io/api-doc

**Comment by yvolk** [comment]
Hello @4ioskd 
Frankly I don't think that I will have time to add support for any new client API without a very good reason.

This is why my question to You is: does Misskey team has a plan to support client-to-server protocol of ActivityPub? Especially since it Misskey already declares ActivityPub server-to-server support.

See https://github.com/andstatus/andstatus/issues/499

**Comment by yvolk** [comment]
I think we better invest our time in support of open and common protocols than in custom ones used by small groups.
And vice versa: Misskey may stay a niche microblogging platform if it doesn't adopt popular client to server API. Simply because of lack of client apps.
