### ISSUE TITLE

Status stuck at Public (unsent) forever 

### ISSUE THREAD

**Issue by DetroitLibertyPenguin** [andstatus/andstatus#556]
I haven't figured out a recipe to reproduce on demand, but frequently I will get status update that never actually get posted to the server.

When it gets in this state nothing seems to fix it. I have tried selecting resend, selecting either of the spinning arrow icons, the sync with intent button and edit to click send again.

About the only thing that works is edit/copy/discard/new status/paste/send. ![Screenshot_20220521-135814_AndStatus.jpg](https://user-images.githubusercontent.com/65328167/169663921-1968dbdb-0776-4b96-a18a-d1b5b73188dc.jpg)

**Comment by yvolk** [comment]
Hi @DetroitLibertyPenguin !
Please try to "Resend" the "unsent" note, and if it is still "unsent", after a a couple of minutes please go to the top menu -> "Commands in a queue" and lookup the command:
```
Post "Text of your note...
```
- there will be some clue on a cause of the error.

**Comment by DetroitLibertyPenguin** [comment]
I've tried a few times since you replied. Maybe I'm blind but I'm not seeing that message at all

I tried changing the logging setting to debug and then the app restarted and took a lot longer to load, and do anything else but still no luck on seeing the POST error.

Sent from my Smartphone please dismiss no-so-smart-typos
________________________________

**Comment by DetroitLibertyPenguin** [comment]
[E; ,.txt](https://github.com/andstatus/andstatus/files/8829288/E.txt)
![Screenshot_20220602-230529_AndStatus](https://user-images.githubusercontent.com/65328167/171779808-9d715efc-5390-4dd9-8ea5-50b97c23b37d.jpg)

**Comment by DetroitLibertyPenguin** [comment]
Inadvertently closed

**Comment by DetroitLibertyPenguin** [comment]
System bug report
[bugreport-a51tfn-SP1A.210812.016-2022-06-02-22-58-41.tar.gz](https://github.com/andstatus/andstatus/files/8829324/bugreport-a51tfn-SP1A.210812.016-2022-06-02-22-58-41.tar.gz)

**Comment by yvolk** [comment]
Hi @DetroitLibertyPenguin. Thank you for the info.
I looked into attached "E.txt" and noticed there: "account: fuat2mb@theres.life/ActivityPub" meaning that you added your account at the https://theres.life **Mastodon** instance as if it is **ActivityPub** instance (technically: AndStatus connects to theres.life using "ActivityPub Client to Server protocol") . This could be a cause of the strange behavior. "Mastodon" instances were known to have only partial "ActivityPub" implementation. I.e. something was known to be missed or to fail at a server side. Technical details and long discussion is here: https://github.com/andstatus/andstatus/issues/499
Your story tells that Mastodon developers made some progress since my previous review, but I didn't investigate this recently. Will do this.

Meanwhile, as an alternative, please try to add another account to the AndStatus app, maybe even the same "fuat2mb@theres.life" but this time choose "Mastodon" type of social network. I think the "Mastodon type" account will work more predictably since this was tested a lot.

Note: AndStatus allows you to have two "fuat2mb@theres.life" in different "Types of social networks", but you may easily get confused, which is which. And of course, you will have message duplications... So if you get confused, you can Remove "ActivityPub" type of account and leave only "Mastodon" type.

**Comment by DetroitLibertyPenguin** [comment]
I apologize for the delay in my response. 

FYI, I did change remove that account and re-add it as Mastodon as you recommend, but I did not see any signifcant change regarding my UNSENT forever issue. I did see far fewer options using that option than my other mastodon account that I have connected as ActivityPub. It appears I have seen similar failures on my other accounts, Pump.io, GNU Social, It does seem to improve if I stay on that screen until the "loading" spinner quits spinning in the lower left corner, rather than posting/replying and then quickly shifting to another screen on the app or out of the app.

**Comment by DetroitLibertyPenguin** [comment]
I went to attach additional screen shots, and i noticed that it doesn't seem like there are any such failures on the account I use most often (Friendica) since I deleted it and readded it as GNU Social rather than Activity Pub (the instance I am on supports both Ostatus and AP) for what that is worth

**Comment by yvolk** [comment]
@DetroitLibertyPenguin Some time ago I fixed background syncing so that can improve posting also... see https://github.com/andstatus/andstatus/issues/557
Regarding resending old "unsent" note: If you don't see "Resend" in the note's context menu. try "Edit" and send again from the Editor...
