### ISSUE TITLE
java.security.cert.CertPathValidatorException (was ClassNotFoundException: org.andstatus.app.net.http.OAuthClientKeysSecret)

### ISSUE THREAD

**Issue by naturzukunft** [andstatus/andstatus#583]
[log.txt](https://github.com/andstatus/andstatus/files/12804991/log.txt)

**Comment by yvolk** [comment]
Reading deeper I see that the stacktrace is of the "Verbose" level logging message. This means that you may ignore it as the "OAuthClientKeys" class is NOT required.

**Comment by yvolk** [comment]
Further in the log file we see "URL: https://dev.rdf-pub.org/.well-known/oauth-authorization-server;
Caused by javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found."
This means that the site was signed by a "Certificate authority" that is not trusted by the client (by Android device...) or some other server misconfiguration (please search for the error message).
For the start I would open the URL by a browser and look up certificate info via it. - I did this now and couldn't get any response...

**Comment by naturzukunft** [comment]
> As I understand, you are building AndStatus yourself?!

No, i'm using the app from fdroid i think.

**Comment by naturzukunft** [comment]
> - I did this now and couldn't get any response...

Hm, it's a lets encrypt certificate. I can browse it from my unix notebook.

![image](https://github.com/andstatus/andstatus/assets/47322487/832b7472-ef22-4c70-bf0c-51cbf7f3be56)

**Comment by naturzukunft** [comment]
If i call the url from the same smartphone with firefox i get also a secure connection:

![image](https://github.com/andstatus/andstatus/assets/47322487/25f199db-e8b1-4fb7-8fff-fc08f898377f)

**Comment by yvolk** [comment]
I checked the address https://dev.rdf-pub.org/.well-known/oauth-authorization-server
using https://www.sslchecker.com/sslchecker
and got on my PC that the certificate is not trusted and I need to install some "chain"/"root" certs:

![image](https://github.com/andstatus/andstatus/assets/207716/7fa8a3dc-fe4e-4ad5-aa01-4f095665de05)

BTW, what you tested could be actually not secure connection...

**Comment by yvolk** [comment]
@naturzukunft See also related issues: https://github.com/andstatus/andstatus/issues/379
BTW, AndStatus has "Insecure SSL" option in the "Social network" settings.

**Comment by yvolk** [comment]
And here we also see the certificate's issues: https://www.ssllabs.com/ssltest/analyze.html?d=dev.rdf-pub.org
